NovaNix/CS-499-Canvas-to-Paper-Tests

src/main/java/io/github/csgroup/quizmaker/App.java
src/main/java/io/github/csgroup/quizmaker/ui/UIManager.java

Adding the frame and JMenu for the UI

---

src/main/java/io/github/csgroup/quizmaker/data/Project.java
src/main/java/io/github/csgroup/quizmaker/data/events/project/ProjectQuizUpdateEvent.java

Added Quiz Support to Projects

---

src/main/java/io/github/csgroup/quizmaker/data/Project.java
src/main/java/io/github/csgroup/quizmaker/data/Question.java
src/main/java/io/github/csgroup/quizmaker/data/QuestionBank.java
src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
src/main/java/io/github/csgroup/quizmaker/data/events/project/ProjectBankUpdateEvent.java
src/main/java/io/github/csgroup/quizmaker/data/events/project/ProjectQuizUpdateEvent.java
src/main/java/io/github/csgroup/quizmaker/data/models/ProjectBankListModel.java

Added ListModel support to a Project's QuestionBanks

---

src/main/java/io/github/csgroup/quizmaker/io/JSONUtils.java
src/main/java/io/github/csgroup/quizmaker/utils/HTMLEntities.java
src/main/java/io/github/csgroup/quizmaker/utils/HTMLUtils.java
src/test/java/io/github/csgroup/quizmaker/testingutils/TestFileUtils.java
src/test/java/io/github/csgroup/quizmaker/tests/utils/HTMLUtilsTests.java
src/test/resources/html/textWithEntities.txt
src/test/resources/html/textWithoutEntities.txt

Add HTML Entity Decoding

---

src/main/java/io/github/csgroup/quizmaker/qti/QTIImportManager.java
src/test/java/io/github/csgroup/quizmaker/tests/QTIImportManagerTest.java

Used the style guide to better format the code.

Changes to the code format

---

src/main/java/io/github/csgroup/quizmaker/data/Project.java

This pull request adds the ability to add the contents of a QTIContents object to a Project. 
Resolves #32

Add Project QTI integration

---

src/main/java/io/github/csgroup/quizmaker/data/Answer.java
src/main/java/io/github/csgroup/quizmaker/data/Question.java
src/main/java/io/github/csgroup/quizmaker/data/QuestionBank.java
src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
src/main/java/io/github/csgroup/quizmaker/data/answers/BlankAnswer.java
src/main/java/io/github/csgroup/quizmaker/data/answers/MatchingAnswer.java
src/main/java/io/github/csgroup/quizmaker/data/answers/SimpleAnswer.java
src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/GeneratedQuiz.java
src/main/java/io/github/csgroup/quizmaker/utils/RandomBag.java
src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java

Add Quiz Generation

---

src/main/java/io/github/csgroup/quizmaker/data/Question.java
src/main/java/io/github/csgroup/quizmaker/data/answers/BlankAnswer.java
src/main/java/io/github/csgroup/quizmaker/data/answers/MatchingAnswer.java
src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
src/main/java/io/github/csgroup/quizmaker/qti/QTIReader.java

Adds a temporary QTI return for testing purposes. Resolves #33

Add Temporary QTI return

---

src/main/java/io/github/csgroup/quizmaker/data/Question.java
src/main/java/io/github/csgroup/quizmaker/data/QuestionBank.java
src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/BankSelection.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/GeneratedQuiz.java
src/main/java/io/github/csgroup/quizmaker/utils/stores/writable/DefaultWritableStore.java

Resolves #57 
I'm not sure about this one just yet, it's a little messy.

Add Stores to many internal DataTypes

---

src/main/java/io/github/csgroup/quizmaker/data/Quiz.java

Added GeneratedQuiz storage

---

src/main/java/io/github/csgroup/quizmaker/data/Quiz.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/GeneratedQuiz.java
src/main/java/io/github/csgroup/quizmaker/data/quiz/QuizMetadata.java
src/main/java/io/github/csgroup/quizmaker/utils/Pair.java
src/main/java/io/github/csgroup/quizmaker/word/TemplateReplacements.java

Add Data Structure for Templates

---

src/main/java/io/github/csgroup/quizmaker/data/Question.java
src/main/java/io/github/csgroup/quizmaker/data/questions/FillInTheBlankQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MatchingQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/MultipleChoiceQuestion.java
src/main/java/io/github/csgroup/quizmaker/data/questions/WrittenResponseQuestion.java

Added Abet Score Questions

---

src/main/java/io/github/csgroup/quizmaker/qti/export/ManifestWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/utils/QTIFileWriter.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/ManifestWriterTest.java

Implement Manifest file writer

---

src/main/java/io/github/csgroup/quizmaker/qti/export/MetaWriter.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/MetaWriterTest.java

QTI Export Meta Writer

---

src/main/java/io/github/csgroup/quizmaker/App.java
src/main/java/io/github/csgroup/quizmaker/ui/components/GeneratePanel.java
src/main/java/io/github/csgroup/quizmaker/ui/dialogs/ExportWordDialog.java
src/main/java/io/github/csgroup/quizmaker/ui/dialogs/GenerateDialog.java
src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java

The word backend and UI now communicate effectively between each other. I had to fix some of the UI Dialog to achieve this, although there is currently one bug: templates will never ask for a points replacement. I have tried to figure out where this is limiting itself but I am pushing what I have now and will most likely fix it in the morning.

Ui-Word Support

---

src/main/java/io/github/csgroup/quizmaker/qti/QTIWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/utils/QTIExportZipper.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/QTIWriterTest.java

Now the QTI writer will be able to generate a zip folder containing the manifest file and the assessment meta file

Integrated Manifest and Assessment Writer

---

src/main/java/io/github/csgroup/quizmaker/ui/dialogs/ExportWordDialog.java
src/main/java/io/github/csgroup/quizmaker/word/WordExporter.java

Now throws an exception if quiz is null and tells the user to generate a quiz. Also added a reference file path to the UI and allowed users to append files.

Word Tweaks

---

src/main/java/io/github/csgroup/quizmaker/qti/mapping/QuestionMapper.java
src/main/java/io/github/csgroup/quizmaker/qti/model/assessment/structure/Item.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/AssessmentContentParserTest.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/QTIContentsTest.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/QuestionMapperTest.java
src/test/resources/g22f4cec28e64e3cad0f8e9ab185267d5.xml

Verified that points are displayed properly for each question and that the answers are shown for short_answer_questions

Updated QTI Import: Points Display and Short_Answer_Question Support

---

src/main/java/io/github/csgroup/quizmaker/qti/QTIWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/AssessmentWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/ManifestWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/MetaWriter.java
src/main/java/io/github/csgroup/quizmaker/qti/export/serializers/question/FillInTheBlankQuestionSerializer.java
src/main/java/io/github/csgroup/quizmaker/qti/export/serializers/question/MatchingQuestionSerializer.java
src/main/java/io/github/csgroup/quizmaker/qti/export/serializers/question/MultipleChoiceQuestionSerializer.java
src/main/java/io/github/csgroup/quizmaker/qti/export/serializers/question/QuestionSerializer.java
src/main/java/io/github/csgroup/quizmaker/qti/export/serializers/question/WrittenResponseQuestionSerializer.java
src/main/java/io/github/csgroup/quizmaker/qti/export/utils/QuestionSerializerFactory.java
src/main/java/io/github/csgroup/quizmaker/ui/dialogs/ExportQTIDialog.java
src/test/java/io/github/csgroup/quizmaker/tests/qti/QTIWriterTest.java

Finished the serializers , implemented the Assessment Writer, and fixed the Manifest and Meta Writer 
Resolves #99 
Resolves #94 
Resolves #6

Implemented full QTI Export

---

src/main/java/io/github/csgroup/quizmaker/ui/QuizPanel.java
src/main/java/io/github/csgroup/quizmaker/ui/banks/BankPanel.java
src/main/java/io/github/csgroup/quizmaker/ui/dialogs/QuestionUsageDialog.java

Added Question Usage Tracking
